apiVersion: v1
kind: PersistentVolume
metadata:
    name: localhost-pv
    labels:
        heptio.com/example: lamp
spec:
    capacity:
      storage: 3Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: "/home/autolab/volume"